languageCode: en
languageName: English
languageDirection: ltr
weight: 1
title: Yang's Blog
params:
  dateFormat: 2 January 2006
  description: A blog about newbie DBA
  author:
    name: Yang
    image: author.png
    bio: Specialized in MySQL, familiar with databases
    headline: "He lives in Taichung City with his SPOF (wife) and two replicas<br>- v1.0 (boy) and v2.0 (girl), both in primary school."
    links:
      - github: https://github.com/YangNianLi
      - linkedin: https://linkedin.com/in/yang-li-60bb4711b
      - email: mailto:babchungyo@gmail.com
